# Generated by Django 6.1.1 on 2026-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.TextField()),
                ('name', models.TextField()),
                ('user', models.TextField()),
                ('password', models.TextField()),
                ('host', models.TextField(max_length=15)),
                ('port', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.TextField()),
                ('table_name', models.TextField()),
                ('schema', models.JSONField()),
            ],
        ),
    ]
