# Generated by Django 6.1.1 on 2026-09-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagementService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('module', models.CharField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_copy', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.IntegerField()),
                ('module', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Duration of the exam review session')),
                ('correction_sheet', models.URLField(blank=True, max_length=500, null=True)),
                ('gradings', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.IntegerField()),
                ('professor_id', models.IntegerField(blank=True, null=True)),
                ('exercice', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ExamManagementService.examreview')),
            ],
        ),
    ]
