# Generated by Django 6.1.1 on 2026-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagementService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='database',
            field=models.CharField(max_length=255),
        ),
    ]
